// Generated by CoffeeScript 1.4.0
(function() {
  var PAGING_SIZE, paginatorSetup, parseMyInt;

  PAGING_SIZE = 25;

  parseMyInt = function(someValue, def) {
    if (def == null) {
      def = 0;
    }
    if (!someValue) {
      someValue = def;
    }
    try {
      return parseInt(someValue.toString(), 10);
    } catch (e) {
      return def;
    }
  };

  module.exports = paginatorSetup = function(opts) {
    var paginatorHandle;
    if (opts == null) {
      opts = {};
    }
    paginatorHandle = function(req, res, next) {
      req.paginated = {};
      req.paginated.count = parseMyInt(req.query['count']);
      req.paginated.page = parseMyInt(req.query['page'], 1) - 1;
      req.paginated.offset = parseMyInt(req.query['offset']);
      if (req.paginated.page < 0) {
        req.paginated.page = 0;
      }
      if (req.paginated.offset < 0) {
        req.paginated.offset = 0;
      }
      if (req.paginated.count < 1 || req.paginated.count > 200) {
        req.paginated.count = PAGING_SIZE;
      }
      return next();
    };
    return paginatorHandle;
  };

}).call(this);
